version: '2'

networks:
  zentao-net:
    driver: bridge

services:

# mysql service for zentao
  zentao-mysql:
    image: mysql:8.0.30
    container_name: zentao-mysql
    ports:
      - '3307:3306'
    volumes:
      - 'zentao_db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=pass4Zentao
      - MYSQL_DATABASE=zentao
    networks:
      - zentao-net

# zentao service
  zentao:
    image: easysoft/quickon-zentao:${TAG:-latest}
    container_name: zentao
    ports:
      - '8080:80'
    volumes:
      - 'zentao_data:/data'
    depends_on:
      - zentao-mysql
    environment:
      - ZT_MYSQL_HOST=zentao-mysql
      - ZT_MYSQL_PORT=3306
      - ZT_MYSQL_USER=root
      - ZT_MYSQL_PASSWORD=pass4Zentao
      - ZT_MYSQL_DB=zentao
      - EASYSOFT_DEBUG=true
      - DEBUG=1
      - IS_CONTAINER=true
    networks:
      - zentao-net

# persistence for mysql and zentao
volumes:
  zentao_db:
    driver: local
  zentao_data:
    driver: local
