version: '3'

env:
  APP_NAME: zentao
  PHP_VER: 7.4.33
  MYSQL_VER: 10.6.15
  BUILD_PUBLIC_IMAGE:
    sh: echo ${CI_BUILD_PUBLIC_IMAGE:-false}
  INTERNAL_IMAGE_REPO:
    sh: echo ${CI_INTERNAL_IMAGE_REPO:-hub.qc.oop.cc}
  INTERNAL_IMAGE_NAMESPACE:
    sh: echo ${CI_INTERNAL_IMAGE_NAMESPACE:-app}
  PUBLIC_IMAGE_REPO:
    sh: echo ${CI_PUBLIC_IMAGE_REPO:-hub.zentao.net}
  PUBLIC_IMAGE_NAMESPACE:
    sh: echo ${CI_PUBLIC_IMAGE_NAMESPACE:-app}
  OPEN_VER:
    sh: echo ${PMS_VERSION:-$(jq -r .zentaopms.version < version.json)}
  BIZ_VER:
    sh: echo ${BIZ_VERSION:-biz$(jq -r .biz.version < version.json)}
  BIZ_K8S_VER:
    sh: echo ${BIZ_VER:-biz$(jq -r .bizk8s.version < version.json).k8s}
  MAX_VER:
    sh: echo ${MAX_VERSION:-max$(jq -r .max.version < version.json)}
  MAX_K8S_VER:
    sh: echo ${MAX_VERSION:-max$(jq -r .maxk8s.version < version.json).k8s}
  LITE_VER:
    sh: echo "lite$(jq -r .litev.version < version.json)"
  LITEBIZ_VER:
    sh: echo "lite$(jq -r .litevipv.version < version.json)"
  IPD_VER:
    sh: echo ${IPD_VERSION:-ipd$(jq -r .ipd.version < version.json)}
  IPD_K8S_VER:
    sh: echo ${IPD_VERSION:-ipd$(jq -r .ipdk8s.version < version.json).k8s}

tasks:
  default:
    desc: 默认列出所有的任务
    cmds:
      - task --list-all

  build:
    desc: 构建内网 开源版
    cmds:
      - /bin/bash ./hack/make-rules/build.sh "$APP_NAME" "$OPEN_VER" "$PHP_VER" "$MYSQL_VER" "linux/amd64,linux/arm64" "Dockerfile" "internal"

  pub-build:
    desc: 手动构建公网 开源版
    aliases: [pb]
    cmds:
      - /bin/bash ./hack/make-rules/public-build.sh "$APP_NAME" "$OPEN_VER" "$PHP_VER" "$MYSQL_VER"

  build-biz:
    desc: 构建内网 企业版
    aliases: [biz]
    cmds:
      - /bin/bash ./hack/make-rules/build.sh "$APP_NAME" "$BIZ_VER" "$PHP_VER" "$MYSQL_VER" "linux/amd64,linux/arm64" "Dockerfile" "internal"

  pub-build-biz:
    desc: 手动构建公网 企业版
    aliases: [pbiz]
    cmds:
      - /bin/bash ./hack/make-rules/public-build.sh "$APP_NAME" "$BIZ_VER" "$PHP_VER" "$MYSQL_VER"

  build-biz-k8s:
    desc: 构建内网 企业K8s版
    aliases: [biz-k8s]
    cmds:
      - /bin/bash ./hack/make-rules/build.sh "$APP_NAME" "$BIZ_K8S_VER" "$PHP_VER" "$MYSQL_VER" "linux/amd64,linux/arm64" "Dockerfile" "internal"

  pub-build-biz-k8s:
    desc: 手动构建公网 企业K8s版
    aliases: [pbiz-k8s]
    cmds:
      - /bin/bash ./hack/make-rules/public-build.sh "$APP_NAME" "$BIZ_K8S_VER" "$PHP_VER" "$MYSQL_VER"

  build-max:
    desc: 构建内网 旗舰版
    aliases: [max]
    cmds:
      - /bin/bash ./hack/make-rules/build.sh "$APP_NAME" "$MAX_VER" "$PHP_VER" "$MYSQL_VER" "linux/amd64,linux/arm64" "Dockerfile" "internal"

  pub-build-max:
    desc: 手动构建公网 旗舰版
    aliases: [pmax]
    cmds:
      - /bin/bash ./hack/make-rules/public-build.sh "$APP_NAME" "$MAX_VER" "$PHP_VER" "$MYSQL_VER"

  build-max-k8s:
    desc: 构建内网 旗舰K8S版
    aliases: [max-k8s]
    cmds:
      - /bin/bash ./hack/make-rules/build.sh "$APP_NAME" "$MAX_K8S_VER" "$PHP_VER" "$MYSQL_VER" "linux/amd64,linux/arm64" "Dockerfile" "internal"

  pub-build-max-k8s:
    desc: 手动构建公网 旗舰K8S版
    aliases: [pmax-k8s]
    cmds:
      - /bin/bash ./hack/make-rules/public-build.sh "$APP_NAME" "$MAX_K8S_VER" "$PHP_VER" "$MYSQL_VER"

  build-ipd:
    desc: 构建内网 IPD版
    aliases: [ipd]
    cmds:
      - /bin/bash ./hack/make-rules/build.sh "$APP_NAME" "$IPD_VER" "$PHP_VER" "$MYSQL_VER" "linux/amd64,linux/arm64" "Dockerfile" "internal"

  pub-build-ipd:
    desc: 手动构建公网 IPD版
    aliases: [pipd]
    cmds:
      - /bin/bash ./hack/make-rules/public-build.sh "$APP_NAME" "$IPD_VER" "$PHP_VER" "$MYSQL_VER"

  build-ipd-k8s:
    desc: 构建内网 IPD K8S版
    aliases: [ipd-k8s]
    cmds:
      - /bin/bash ./hack/make-rules/build.sh "$APP_NAME" "$IPD_K8S_VER" "$PHP_VER" "$MYSQL_VER" "linux/amd64,linux/arm64" "Dockerfile" "internal"

  pub-build-ipd-k8s:
    desc: 手动构建公网 IPD K8S版
    aliases: [pipd-k8s]
    cmds:
      - /bin/bash ./hack/make-rules/public-build.sh "$APP_NAME" "$IPD_K8S_VER" "$PHP_VER" "$MYSQL_VER"

  build-all:
    desc: 构建内网 所有版本
    aliases: [all]
    deps: [build,biz,biz-k8s,max,max-k8s,ipd,ipd-k8s]

  pub-build-all:
    desc: 手动构建公网 所有版本
    aliases: [pall]
    deps: [pb,pbiz,pbiz-k8s,pmax,pmax-k8s,pipd,pipd-k8s]
