#!/bin/bash

# shellcheck disable=SC1091
. /etc/s6/s6-init/envs
. /opt/easysoft/scripts/libmysql.sh

set -e

[ -n "${DEBUG:+1}" ] && set -x

if [ "$MYSQL_INTERNAL" == "true" ];then
    s6-svwait -u -t 30000 /etc/s6/s6-available/mysql
fi

# Just for debug
sleep "${PAUSE:-0}"

# Check and waiting mysql to be ready
wait_for_mysql || exit 1

# wait for zentao installation finished
while ((1))
do
    if [ -f /data/zentao/.version ];then
        break
    fi
    sleep 1
done

exec /usr/bin/rr serve -c /apps/zentao/roadrunner/.rr.yaml
