#!/bin/bash

# shellcheck disable=SC1091

[ -n "${DEBUG:+1}" ] && set -x

# Load libraries
. /opt/easysoft/scripts/liblog.sh
. /opt/easysoft/scripts/libmysql.sh
. /etc/s6/s6-init/envs

case $ZENTAO_VER in
"litevip1.2")
    export ZENTAO_VER="biz7.1"
    ;;
"lite1.2")
    export ZENTAO_VER="17.1"
    ;;
*)
    export ZENTAO_VER=${ZENTAO_VER/.k8s/}
    ;;
esac

MYSQL_BIN="/usr/bin/mysql --host=$MYSQL_HOST --port=$MYSQL_PORT --user=$MYSQL_USER --password=$MYSQL_PASSWORD -D$MYSQL_DB"
TABLE_PREFIX=$(grep prefix /data/zentao/config/my.php  | cut -d '=' -f 2 | sed -E "s/( |'|;)//g")
export TABLE_PREFIX=${TABLE_PREFIX:-zt_}
FIRST_RUN=$( [ -e /data/zentao/.version ] && grep $ZENTAO_VER /data/zentao/.version )
export CHECK_LOG="/tmp/check_file.log"
export LDAP_SQL="/apps/zentao/config/ldap.sql"
export SMTP_SQL="/apps/zentao/config/smtp.sql"
[ ! -e $CHECK_LOG ] && touch $CHECK_LOG

# Founction: Config LDAP
function Config_LDAP()
{
    /usr/bin/render-template ${LDAP_SQL}.tpl > $LDAP_SQL

    # 清理禅道ldap配置
    $MYSQL_BIN -e "DELETE from ${TABLE_PREFIX}config where owner='system' and module='ldap';" | tee $CHECK_LOG

    # 如果开启LDAP，导入LDAP配置
    if [ "$LDAP_ENABLED" == "1" ];then
        info "Enable LDAP ..."
        mysql_import_to_db "$MYSQL_DB" "$LDAP_SQL" | tee $CHECK_LOG
    fi
}


# Founction: Config SMTP
function Config_SMTP()
{
    /usr/bin/render-template ${SMTP_SQL}.tpl > $SMTP_SQL

    # 判断并设置发件人
    SENDER=$($MYSQL_BIN -e "select * from ${TABLE_PREFIX}config where \`key\`='fromName'";)
    if [ "$SENDER" == "" ];then
        $MYSQL_BIN -e "REPLACE INTO ${TABLE_PREFIX}config (\`vision\`,\`owner\`,\`module\`,\`section\`,\`key\`,\`value\`) VALUES ('','system','mail','','fromName',\"${SMTP_FROMNAME}\");"
    fi

    # 清理禅道 SMTP 配置
    $MYSQL_BIN -e "DELETE from ${TABLE_PREFIX}config where owner='system' and module='mail' and \`key\`<>'fromName';" | tee $CHECK_LOG

    # 如果开启 SMTP，导入SMTP配置
    if [ "$SMTP_ENABLED" == "1" ];then
        info "Enable SMTP ..."
        mysql_import_to_db "$MYSQL_DB" "$SMTP_SQL" | tee $CHECK_LOG
    fi

}

while ((1))
do

    CFG_INITED=$(wc -l /apps/zentao/config/my.php | awk '{print $1}')

    # Installed successfully
    if [ "$CFG_INITED" != "0" ];then
        CURRENT_VER=$($MYSQL_BIN -e "select value from \`${TABLE_PREFIX}config\` where  \`section\`='global' and \`key\`='version';" 2>/dev/null | sed 1d )
    fi

    # Check and config ldap/smtp
    if [ "$CURRENT_VER" != "" ];then
        Config_LDAP
        Config_SMTP
    fi

    # If the initial installation is successful, delete install.php andupgrade.php files
    if [ "$CURRENT_VER" == "$ZENTAO_VER" ] && [ "$CFG_INITED" != "0" ];then

        if [ "$FIRST_RUN" == "" ];then
            echo "$(date +'%F %H:%M:%S') $ZENTAO_VER installed" >> /data/zentao/.version
            sleep 30
        fi
      
        # remove install and update file
        rm -f /apps/zentao/www/{install.php,upgrade.php}
        
        info "Zentao installation complete."

	    break 
    fi

    # ZenTao upgrade, remove only the install.php file 
    if [ "$CURRENT_VER" != "" ] && [ "$CURRENT_VER" != "$ZENTAO_VER" ] && [ "$CFG_INITED" != "0" ];then
        rm -f /apps/zentao/www/install.php
	    echo "$(date +'%F %H:%M:%S') $CURRENT_VER update to $ZENTAO_VER" >> /data/zentao/.version
        info "Zentao upgrade is complete."
       	break
    fi

    warn "Please open the browser to complete the installation through the wizard."
    sleep 1

done

exec tail -f $CHECK_LOG