#!/bin/bash

# shellcheck disable=SC1091
. /etc/s6/s6-init/envs
. /opt/easysoft/scripts/liblog.sh
. /opt/easysoft/scripts/libcomm.sh
. /opt/easysoft/scripts/libmysql.sh
. /opt/easysoft/scripts/libphp.sh
. /opt/easysoft/scripts/libdevops.sh

set -e

[ -n "${DEBUG:+1}" ] && set -x

if [ "$MYSQL_INTERNAL" == "true" ];then
    s6-svwait -u -t 30000 /etc/s6/s6-available/mysql
fi

wait_for_service "MySQL" "$ZT_MYSQL_HOST" "$ZT_MYSQL_PORT" "apache" || exit 1

# Just for debug
sleep "${PAUSE:-0}"


# link mysql.sock for mysql client
if [ -e /data/mysql/tmp/mysql.sock ] && [ ! -L /opt/zbox/tmp/mysql/mysql.sock ];then
    ln -s /data/mysql/tmp/mysql.sock /opt/zbox/tmp/mysql/mysql.sock
fi

# First run add user and grant privileges
if [ "$MYSQL_INTERNAL" == "true" ] && [ ! -f /data/zentao/.version ] ;then
    mysql_reset_password
fi

# Initialize database
mysql -h"$ZT_MYSQL_HOST" -P"$ZT_MYSQL_PORT" -u"$ZT_MYSQL_USER" -p"$ZT_MYSQL_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $ZT_MYSQL_DB; "

# Check DEVOPS mode and init
if [[ $IN_QUICKON == "true" && $DEVOPS == "true" ]]; then
    Init_Quickon_DevOps
fi

# Enable or disable php extensions
control_php_ext

exec /opt/zbox/bin/apachectl -D FOREGROUND > /dev/null 2>&1
