#!/bin/bash

# shellcheck disable=SC1091
. /etc/s6/s6-init/envs
. /opt/easysoft/scripts/libmysql.sh

set -e

[ -n "${DEBUG:+1}" ] && set -x

if [ "$MYSQL_INTERNAL" == "true" ];then
    s6-svwait -u -t 30000 /etc/s6/s6-available/mysql
fi

# Just for debug
sleep "${PAUSE:-0}"

# Check and waiting mysql to be ready
wait_for_mysql || exit 1

# link mysql.sock for mysql client
if [ -e /data/mysql/tmp/mysql.sock ] && [ ! -L /opt/zbox/tmp/mysql/mysql.sock ];then
    ln -s /data/mysql/tmp/mysql.sock /opt/zbox/tmp/mysql/mysql.sock
fi

# First run add user and grant privileges
if [ "$MYSQL_INTERNAL" == "true" ] && [ ! -f /data/zentao/.version ] ;then
    mysql_reset_password
fi

# Initialize database
mysql -h"$ZT_MYSQL_HOST" -P"$ZT_MYSQL_PORT" -u"$ZT_MYSQL_USER" -p"$ZT_MYSQL_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $ZT_MYSQL_DB; "

exec /opt/zbox/bin/apachectl -D FOREGROUND
