#!/bin/bash

# shellcheck disable=SC1091
. /etc/s6/s6-init/envs
. /opt/easysoft/scripts/libmysql.sh

set -e

[ -n "${DEBUG:+1}" ] && set -x

#======================#
# Check MySQL service  #
#======================#
# Check and waiting mysql to be ready
wait_for_mysql || exit 1

# link mysql.sock for mysql client
if [ -f /data/mysql/tmp/mysql.sock ];then
    ln -s /data/mysql/tmp/mysql.sock /opt/zbox/tmp/mysql/mysql.sock
fi

# First run add user and grant privileges
if [ "$MYSQL_INTERNAL" == "true" ] && [ ! -f /data/zentao/.version ] ;then
    mysql -h127.0.0.1 -uroot -p123456 \
          -e "CREATE USER $MYSQL_USER@'%' IDENTIFIED BY \"$MYSQL_PASSWORD\";GRANT ALL ON *.* TO $MYSQL_USER@'%';flush privileges;"
fi

# Initialize database
mysql -uroot -p"$MYSQL_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DB; "

exec /opt/zbox/bin/apachectl -D FOREGROUND
