#!/bin/bash

# shellcheck disable=SC1091

[ -n "${DEBUG:+1}" ] && set -x

# Load libraries
. /etc/s6/s6-init/envs
. /opt/easysoft/scripts/liblog.sh
. /opt/easysoft/scripts/libcomm.sh
. /opt/easysoft/scripts/libmysql.sh
. /opt/easysoft/scripts/libldap.sh
. /opt/easysoft/scripts/libsmtp.sh
. /opt/easysoft/scripts/libgit.sh
. /opt/easysoft/scripts/libci.sh
. /opt/easysoft/scripts/libscan.sh

# Wait apache to be ready
wait_for_service "apache" "127.0.0.1" "80" "Sentry" || exit 1

export ZENTAO_VER=${ZENTAO_VER/.k8s/}

FIRST_RUN=$( [ -e /data/zentao/.version ] && grep "$ZENTAO_VER" /data/zentao/.version )
export CHECK_LOG="/tmp/sentry.log"
[ ! -e $CHECK_LOG ] && touch $CHECK_LOG


# 持续运行，监控安装向导进度
while ((1))
do

    CFG_INITED=$(wc -l /apps/zentao/config/my.php | awk '{print $1}')

    # Installed successfully
    # 初始化数据库完成
    if [ "$CFG_INITED" != "0" ];then
        TABLE_PREFIX=$(grep prefix /data/zentao/config/my.php  | cut -d '=' -f 2 | sed -E "s/( |'|;)//g")
        export TABLE_PREFIX=${TABLE_PREFIX:-zt_}

        # Just for debug
        sleep "${PAUSE:-0}"

        CURRENT_VER=$(Get_Running_Ver)
        export CURRENT_VER
    fi

    # Check and config ldap/smtp
    # 账号初始化完成
    if [ "$CURRENT_VER" != "" ];then
        Config_LDAP
        Config_SMTP

        # 是否连接Git服务
        if [ "$LINK_GIT" == "true" ];then
            Config_Git
        else
            Clean_Git_Config
        fi
        # 是否配置CI服务
        if [ "$LINK_CI" == "true" ];then
            Config_CI
        else
            Clean_CI_Config
        fi
        # 是否配置SCAN服务
        if [ "$LINK_SCAN" == "true" ];then
            Config_SCAN
        else
            Clean_SCAN_Config
        fi
    fi

    # If the initial installation is successful, delete install.php andupgrade.php files
    # 数据库中的版本号与镜像版本一致，且完成了安装向导
    if [ "$CURRENT_VER" == "$ZENTAO_VER" ] && [ "$CFG_INITED" != "0" ];then

        # 首次安装，标记安装信息
        if [ "$FIRST_RUN" == "" ];then
            echo "$(date +'%F %H:%M:%S') $ZENTAO_VER installed" >> /data/zentao/.version
        fi
        # 兼容老版本升级, 后续移除
        if [ -f /data/.installed.tmp ] && [ ! -f /data/zentao/tmp/.installed.tmp ];then
            mv /data/.installed.tmp /data/zentao/tmp/.installed.tmp
        fi
        # remove install and update file
        # patch for create the .installed.tmp file
        [ -f /data/zentao/tmp/.installed.tmp ] && rm -f /apps/zentao/www/{install.php,upgrade.php}
        info "Zentao is ready to use."

        break
    fi

    # 安装完成，切换了版本
    if [ "$CURRENT_VER" != "" ] && [ "$CURRENT_VER" != "$ZENTAO_VER" ] && [ "$CFG_INITED" != "0" ];then

        rm -f /apps/zentao/www/install.php
        echo "$(date +'%F %H:%M:%S') $CURRENT_VER update to $ZENTAO_VER" >> /data/zentao/.version
        info "Zentao upgrade is complete."
        break
    fi

    # 当配置文件为空时，说明安装向导未完成
    if [ "$CFG_INITED" == "0" ];then
        info "Waiting for the installation wizard to complete."
    fi
    sleep 1

done

exec tail -f $CHECK_LOG
