#!/bin/bash

OS_ARCH=$(uname -m)
if [ "$OS_ARCH" == "x86_64" ];then
    export OS_ARCH="amd64"
else
    export OS_ARCH="arm64"
fi


PHP_CLASSIFIER="php7.2_7.4"
if [[ "$PHP_VER" =~ ^8\.1 ]];then
    PHP_CLASSIFIER="php8.1"
fi
export PHP_CLASSIFIER