#!/bin/bash

#==========#
# Global   #
#==========#
export IS_CONTAINER="true"
export PROTOCOL_TYPE=${PROTOCOL_TYPE:-https}
export ZENTAO_TOKEN_NAME=${ZENTAO_TOKEN_NAME:-quickon-zentao}
#==========#
#  DevOps  #
#==========#
# Link Git
export LINK_GIT=${LINK_GIT:-false}
export GIT_TYPE=${GIT_TYPE:-gitea}
export GIT_INSTANCE_NAME=${GIT_INSTANCE_NAME:-"QuickOn-Gitea"}
export GIT_USERNAME=${GIT_USERNAME:-"root"}
export GIT_PASSWORD=${GIT_PASSWORD:-"pass4QuickOn"}
export GIT_PROTOCOL=${GIT_PROTOCOL:-"https"}
export GIT_DOMAIN=${GIT_DOMAIN:-"git.haogs.cn"}
export GIT_SQL_FILE="/apps/zentao/config/git.sql"

#==========#
# CI  #
#==========#
export LINK_CI=${LINK_CI:-false}
export CI_TYPE=${CI_TYPE:-"jenkins"}
export CI_USERNAME=${CI_USERNAME:-"root"}
export CI_PASSWORD=${CI_PASSWORD:-"pass4QuickOn"}
export CI_PROTOCOL=${CI_PROTOCOL:-"https"}
export CI_URL=${CI_URL:-"jenkins.haogs.cn"}
export CI_SQL_FILE="/apps/zentao/config/ci.sql"

#==========#
#   php    #
#==========#
export PHP_SESSION_TYPE=${PHP_SESSION_TYPE:-files}
export PHP_SESSION_PATH=${PHP_SESSION_PATH:-/data/php/session}
export PHP_ERROR_LOG=${PHP_ERROR_LOG:-/data/php/log/error.log}
export PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-120}
export PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-256M}
export PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-128M}
export PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-128M}

#==========#
#   LDAP   #
#==========#
LDAP_ENABLED=${LDAP_ENABLED:-false}
if [ "$LDAP_ENABLED" == "true" ];then
	export LDAP_ENABLED=1
else
	export LDAP_ENABLED=0
fi
export LDAP_HOST=${LDAP_HOST:-127.0.0.1}
export LDAP_PORT=${LDAP_PORT:-389}
export LDAP_ADMINUSER=${LDAP_ADMINUSER:-cn=admin,dc=quickon,dc=org}
export LDAP_BINDPASSWORD=${LDAP_BINDPASSWORD:-pass4zenTao}
export LDAP_BASEDN=${LDAP_BASEDN:-dc=quickon,dc=org}
export LDAP_USERKEY=${LDAP_USERKEY:-uid}
export LDAP_EMAILKEY=${LDAP_EMAILKEY:-mail}

#==========#
#   SMTP   #
#==========#
SMTP_ENABLED=${SMTP_ENABLED:-false}
if [ "$SMTP_ENABLED" == "true" ];then
	export SMTP_ENABLED=1
else
	export SMTP_ENABLED=0
fi
export SMTP_HOST=${SMTP_HOST:-127.0.0.1}
export SMTP_PORT=${SMTP_PORT:-25}
export SMTP_USER=${SMTP_USER:-zentao@easycorp.cn}
export SMTP_PASS=${SMTP_PASS:-pass4zenTao}
export SMTP_FROMNAME=${SMTP_FROMNAME:-ZenTao $ZENTAO_VER}

#===========#
#   MySQL   #
#===========#
export MYSQL_HOST=${MYSQL_HOST:-127.0.0.1}
export MYSQL_PORT=${MYSQL_PORT:-3306}
export MYSQL_DB=${MYSQL_DB:-zentao}
export MYSQL_USER=${MYSQL_USER:-root}
export MYSQL_PASSWORD=${MYSQL_PASSWORD:-pass4Zentao}

#==========#
# Apache   #
#==========#
export APP_DOMAIN=${APP_DOMAIN:-*}
export APP_DEFAULT_PORT=${APP_DEFAULT_PORT:-80}
export DOCUMENT_ROOT=${DOCUMENT_ROOT:-/apps/zentao/www}

# ======================#
# Persistence directory #
#=======================#
export PHP_PERSISTENCE_LIST=(
"/data"
"/data/php"
"/data/php/log"
"/data/php/session"
"/data/zentao")

#==========================================#
# Persistence directory and make soft link #
#==========================================#
export PERSISTENCE_LINK_LIST=(
"/data/zentao/config/my.php"
"/data/zentao/config/license"
"/data/zentao/config/ext"
"/data/zentao/www/data"
"/data/zentao/tmp/log"
"/data/zentao/tmp/template"
"/data/zentao/tmp/backup"
"/data/zentao/module/extension/ext"
"/data/zentao/extension/custom")
