#!/bin/bash

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail

[ -n "${DEBUG:+1}" ] && set -x

# Load libraries
. /opt/easysoft/scripts/envs
. /opt/easysoft/scripts/liblog.sh
. /opt/easysoft/scripts/libpersistence.sh

# Load Global/Apache/PHP environment variables
. /etc/s6/s6-init/envs

#==================================#
# Prepare persistence directories. #
#==================================#
info "Prepare persistence directories."
for pdir in "${PHP_PERSISTENCE_LIST[@]}"
do
    # Ensure a directory exists and,is owned by the given user
    ensure_dir_exists "$pdir" "nobody"  "nogroup"
done

# Make soft link for persistent directory
for ldir in "${PERSISTENCE_LINK_LIST[@]}"
do
    ensure_dir_exists "$(dirname "$ldir")" "nobody"  "nogroup"
    move_then_link "$ldir" "${ldir/data/apps}" "nobody"  "nogroup"
done

#=====================#
#   Prepare PHP       #
#=====================#
info "Render php.ini with environment variables."
PHP_INI="/opt/zbox/etc/php/php.ini"
/usr/bin/render-template ${PHP_INI}.tpl > ${PHP_INI}

# enable redis extension
if [ "$PHP_SESSION_TYPE" == "redis" ];then
    info "Enable redis extension for session."  
    phpenmod redis

    if [ "$PHP_REDIS_SENTINEL" == "true" ];then
        ini_file=$(ls /opt/zbox/etc/php/conf.d/*-redis.ini)
        echo "redis.sentinel = 1" >> "$ini_file"
    fi
fi

#=====================#
#   Prepare Apache    #
#=====================#
HTTPD_CONF="/opt/zbox/etc/apache/httpd.conf"

info "Render apache sites config with envionment variables."
/usr/bin/render-template ${HTTPD_CONF}.tpl > $HTTPD_CONF

#=====Set Zentao Config=====
# Disable checkClient fix QuickOn DevOps
cfg_num=$(grep -n checkClient /apps/zentao/config/config.php | awk -F ':'  '{print $1}')
sed -i "$cfg_num s/true/false/" /apps/zentao/config/config.php

#================================#
#   Prepare custom extensions    #
#================================#
info "Prepare custom extensions."
#for ext in $(ls -1 /apps/zentao/extension/pkg )
for ext in $(ls -1 /apps/zentao/module/extension/ext/ )
do
    #if [ -f "/apps/zentao/extension/pkg/$ext/disabled" ];then
    if [ -f "/apps/zentao/module/extension/ext/$ext/disabled" ];then
        info "Skip disabled extension $ext"
        continue
    else
        info "Install extension $ext"
        #cp -rp /apps/zentao/extension/pkg/$ext/* /apps/zentao/
        cd /apps/zentao/module/extension/ext/$ext \
        && tar -cf - . | tar -xf  -  -C /apps/zentao/ --keep-directory-symlink
    fi
done